This is makeindex, version 2.15 [MiKTeX 2.9.6500 64-bit] (kpathsea + Thai support).
Scanning style file ./02_EstadoArte.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 02_EstadoArte.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file 02_EstadoArte.acr....done (6 lines written, 0 warnings).
Output written in 02_EstadoArte.acr.
Transcript written in 02_EstadoArte.alg.
