This is makeindex, version 2.15 [MiKTeX 2.9.6630 64-bit] (kpathsea + Thai support).
Scanning style file ./Main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Main.acn....done (15 entries accepted, 0 rejected).
Sorting entries....done (62 comparisons).
Generating output file Main.acr....done (41 lines written, 0 warnings).
Output written in Main.acr.
Transcript written in Main.alg.
